name: Coverity (Ubuntu 20.04, Python 3.11)
on:
  workflow_dispatch:
    inputs:
      openvinoRef:
        description: 'Branch, tag or commit hash to clone openvino from. Taken from event context if not set'
        type: string
      openvinoContribRef:
        description: 'Branch, tag or commit hash to clone openvino_contrib from. Taken from event context if not set'
        type: string
      target-branch:
        description: 'Target branch for the build; taken from event context by default'
        type: string
        required: false
  schedule:
    # run daily at 00:00
    - cron: '0 0 * * *'

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-linux-coverity
  cancel-in-progress: true

permissions: read-all

env:
  PIP_CACHE_PATH: /mount/caches/pip/linux
  PYTHON_VERSION: '3.11'
  TARGET_BRANCH: ${{ inputs.target-branch || github.base_ref || github.event.merge_group.base_ref || github.ref }}

jobs:
  
  Smart_CI:
    runs-on: ubuntu-latest
    outputs:
      affected_components: "${{ steps.smart_ci.outputs.affected_components }}"
      changed_components: "${{ steps.smart_ci.outputs.changed_components }}"
      skip_workflow: "${{ steps.smart_ci.outputs.skip_workflow }}"
    steps:
      - name: checkout action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          sparse-checkout: .github/actions/smart-ci

      - name: Get affected components
        id: smart_ci
        uses: ./.github/actions/smart-ci
        with:
          repository: ${{ github.repository }}
          pr: ${{ github.event.number }}
          commit_sha: ${{ github.sha }}
          ref_name: ${{ github.ref_name }}
          component_pattern: "category: (.*)"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_when_only_listed_labels_set: 'docs'
          skip_when_only_listed_files_changed: '*.md,*.rst,*.png,*.jpg,*.svg'
  
  Docker:
    needs: Smart_CI
    runs-on: aks-linux-4-cores-16gb-docker-build
    container:
      image: openvinogithubactions.azurecr.io/docker_build:0.2
      volumes:
        - /mount:/mount
    outputs:
      images: "${{ steps.handle_docker.outputs.images }}"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15

      - uses: ./.github/actions/handle_docker
        id: handle_docker
        with:
          images: |
            ov_build/ubuntu_20_04_x64
          registry: 'openvinogithubactions.azurecr.io'
          dockerfiles_root_dir: '.github/dockerfiles'
          changed_components: ${{ needs.smart_ci.outputs.changed_components }}
            
  Build:
    needs: Docker
    timeout-minutes: 150
    defaults:
      run:
        shell: bash
    runs-on: aks-linux-16-cores-32gb
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    container:
      image: ${{ fromJSON(needs.docker.outputs.images).ov_build.ubuntu_20_04_x64 }}
      volumes:
        - /mount:/mount
    env:
      DEBIAN_FRONTEND: noninteractive # to prevent apt-get from waiting user input
      CMAKE_BUILD_TYPE: 'Release'
      CMAKE_GENERATOR: 'Ninja Multi-Config'
      GITHUB_WORKSPACE: '/__w/openvino/openvino'
      OPENVINO_REPO: /__w/openvino/openvino/openvino
      OPENVINO_CONTRIB_REPO: /__w/openvino/openvino/openvino_contrib
      BUILD_DIR: /__w/openvino/openvino/openvino_build
      COVERITY_TOOL_DIR: /__w/openvino/openvino/coverity_tool

    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          path: ${{ env.OPENVINO_REPO }}
          submodules: 'true'
          ref: ${{ inputs.openvinoRef }}

      - name: Clone OpenVINO Contrib
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          repository: 'openvinotoolkit/openvino_contrib'
          path: ${{ env.OPENVINO_CONTRIB_REPO }}
          submodules: 'true'
          ref: ${{ inputs.openvinoContribRef || env.TARGET_BRANCH }}

      #
      # Dependencies
      #

      - name: Install build dependencies
        run: |
          bash ${OPENVINO_REPO}/install_build_dependencies.sh
          # default-jdk - Java API
          apt install --assume-yes --no-install-recommends default-jdk

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: ./openvino/.github/actions/setup_python
        with:
          version: ${{ env.PYTHON_VERSION }}
          pip-cache-path: ${{ env.PIP_CACHE_PATH }}
          should-setup-pip-paths: 'true'
          self-hosted-runner: 'true'

      #
      # Build
      #
        
      - name: CMake configure - OpenVINO
        run: |
          cmake \
            -G "${{ env.CMAKE_GENERATOR }}" \
            -DENABLE_CPPLINT=OFF \
            -DENABLE_STRICT_DEPENDENCIES=OFF \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DENABLE_FASTER_BUILD=OFF \
            -S ${OPENVINO_REPO} \
            -B ${BUILD_DIR}

      - name: Install Coverity tool
        run: |
          rm -rf ${COVERITY_TOOL_DIR} && mkdir -p ${COVERITY_TOOL_DIR}
          pushd ${COVERITY_TOOL_DIR}
            wget https://ubit-artifactory-or.intel.com/artifactory/coverity-or-local/Enterprise/license.dat -O license.dat
            wget https://ubit-artifactory-or.intel.com/artifactory/coverity-or-local/Enterprise/cov-analysis-linux64-2024.6.1.sh -O cov-analysis-2024.6.1.sh
            chmod u+x cov-analysis-2024.6.1.sh
            ./cov-analysis-2024.6.1.sh --unattended --skip-license --prefix ${COVERITY_TOOL_DIR}
            ./cov-analysis-2024.6.1.sh \
              -q \
              --installation.dir=${COVERITY_TOOL_DIR} \
              --license.agreement=agree \
              --license.region=0 \
              --license.type.choice=0 \
              --license.cov.path=${COVERITY_TOOL_DIR}/license.dat \
              --component.sdk=false \
              --component.skip.documentation=true
            rm cov-analysis-2024.6.1.sh
            export PATH=$PATH:${COVERITY_TOOL_DIR}/bin/
          popd

      - name: Cmake build - OpenVINO with Coverity (create coverity artifacts)
        run: cov-build --dir ${BUILD_DIR}/cov-int cmake --build ${BUILD_DIR} --parallel $(nproc) --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Coverity - analyze created artifacts
        run: |
          cov-manage-emit --dir cov-int --tu-pattern "file('/usr/.*')" delete
          cov-manage-emit --dir cov-int --tu-pattern "file('/thirdparty/.*')" delete
          cov-manage-emit --dir cov-int --tu-pattern "file('/src/plugins/intel_gpu/thirdparty/.*')" delete
          cov-manage-emit --dir cov-int --tu-pattern "file('/src/plugins/intel_cpu/thirdparty/.*')" delete
          cov-manage-emit --dir cov-int --tu-pattern "file('/src/plugins/intel_npu/thirdparty/.*')" delete
          cov-manage-emit --dir cov-int --tu-pattern "file('/build/.*')" delete
          cov-manage-emit --dir cov-int --tu-pattern "file('/docs/.*')" delete
          cov-analyze \
          --dir ${BUILD_DIR}/cov-int \
          --concurrency \
          --security \
          --rule --enable-constraint-fpp --enable-fnptr --enable-virtual --enable-default --webapp-security --enable-audit-checkers --enable-audit-mode \
          --strip-path ${{ env.OPENVINO_REPO }}

      - name: Submit artefacts
        run: |
        	cov-commit-defects \
            --dir cov-int \
            --stream OpenVINO-master-stream \
            --url  https://coverityent.devtools.intel.com/prod1 \
            --version "${{ github.sha }}" \
            --user <user> \
            --password <coverity> \
            --strip-path ${{ env.OPENVINO_REPO }} --noxrefs

      - name: Show Coverity configure logs
        continue-on-error: true
        run: cov-configure -c ${COVERITY_TOOL_DIR}/coverity_config.xml -lscc text

      - name: Upload Coverity build log
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: coverity_logs
          path: ${{ env.BUILD_DIR }}/cov-int/build-log.txt
          if-no-files-found: 'error'
